showroom/urls.py
from showroom import views
from django.urls import path

urlpatterns = [
    path('dashboard/', views.index),
    path('admin/', views.login),
    path('logout/', views.logout),
   
    # .......for branch...........
    path('', views.branch_login),
    path('login/', views.branch_login),
    path('signout/', views.branch_logout),
    path('my-dashboard/', views.branch_dashboard),
    path('add-area/', views.add_area),
    path('area-list/', views.area_list),
    path('edit-area/<int:id>/', views.edit_area),
    path('customer-registration/', views.customer_reg),
    path('edit-customer/<int:id>/', views.edit_customer),
    path('customer-list/', views.customer_list),
    path('profile/<int:id>', views.customer_details),
    path('cash-sales-product/',views.cash_selling_product),
    path('installment-sales-product/',views.installment_selling_product),
    path('sold-product-list/',views.sold_product_list),
    path('customer-product-list/',views.customer_product_list),
    path('installment-collection/',views.installment_collection),
    path('installment-list/',views.installment_list),
    path('<int:id>/installment-details/',views.installment_details),
    path('category/product-load/',views.load_category_product),
    path('product-load/',views.load_product),
     path('add-category/', views.add_product_cat),
    path('category-list/', views.category_list),
    path('edit-category/<int:id>', views.edit_product_cat),
    path('delete-category/<int:id>', views.delete_pro_category),
    path('add-brance/', views.add_branch),
    path('edit/<int:id>', views.edit_branch),
    path('remove/<int:id>/', views.delete_branch),
    path('branch-list/', views.branch_list),
    path('add-product/', views.add_product),
    path('product-list/', views.product_list),
    path('change-password/', views.change_password),
    path('details/<int:id>/', views.product_details),
    path('unpaid-list/', views.unpaid_list),
    path('dateover-due-list/', views.dateover_due_list),
    # ................Report.......................

    # ....For Admin........
    path('daily-reports/', views.admin_daily_report),
    path('monthly-reports/', views.admin_monthly_report),
    path('yearly-reports/', views.admin_yearly_report),

    # ....For branch........
    path('daily-report/', views.daily_report),
    path('monthly-report/', views.monthly_report),
    path('yearly-report/', views.yearly_report),
    path('date-wise-report/', views.date_to_date_report),
    path('unpaid-report/', views.unpaid_report),
    path('dateover-due-report/', views.dateover_due_report),
]

showroommanagement/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('super-admin/', admin.site.urls),
    path('',include('showroom.urls')),
    path('/',include('showroom.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showroom/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils import timezone

class CompanyInfo(models.Model):
    com_name         = models.CharField(max_length=150)
    owner_name       = models.CharField(max_length=100)
    email            = models.CharField(max_length=50, blank=True)
    mobile1          = models.CharField(max_length=50, blank=True)
    mobile2          = models.CharField(max_length=50, blank=True)
    domain_url       = models.CharField(max_length=100)
    company_logo     = models.ImageField(upload_to="company_logo/", blank=True)
    staring_year     = models.IntegerField()
    address          = models.TextField(max_length=500, blank=True)
    status           = models.BooleanField(default=True)

    def __str__(self):
        return self.com_name

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Company Information'

class Branches(models.Model):
    branch_name      = models.CharField(max_length=100)
    proprietor_name  = models.CharField(max_length=100)
    branch_logo      = models.ImageField(upload_to="branch_logo/", blank=True)
    user_name        = models.CharField(max_length=50, blank=True)
    email            = models.CharField(max_length=50, blank=True)
    mobile           = models.CharField(max_length=50, blank=True)
    password         = models.CharField(max_length=100)
    staring_year     = models.IntegerField()
    address          = models.TextField(max_length=500, blank=True)
    status           = models.BooleanField(default=True)

    def __str__(self):
        return self.branch_name

    class Meta:
        verbose_name        ='Branch'
        verbose_name_plural ='Branches'

class Area(models.Model): 
    branch         = models.ForeignKey(Branches, on_delete=models.CASCADE)  
    area_name      = models.CharField(max_length=100)
    status         = models.BooleanField(default=True)

    def __str__(self):
        return self.area_name

    class Meta:
        verbose_name        ='Area'
        verbose_name_plural ='Areas'

class CustomerRegistration(models.Model):
    area                  = models.ForeignKey(Area, on_delete=models.CASCADE)
    branch                = models.ForeignKey(Branches, on_delete=models.CASCADE)
    name                  = models.CharField(max_length=50)
    email                 = models.EmailField(max_length=80,blank=True)
    mobile                = models.CharField(max_length=16)
    mobile1               = models.CharField(max_length=16,blank=True)
    nid_number            = models.CharField(max_length=50)
    customer_image        = models.ImageField(upload_to="customer_image/", blank=True)
    nid_image             = models.ImageField(upload_to="nid_image/", blank=True)
    present_address       = models.TextField(blank=True)
    permanent_address     = models.TextField(blank=True)
    profession            = models.CharField(max_length=150,blank=True)
    reference_person      = models.CharField(max_length=50)
    reference_address     = models.CharField(max_length=150)
    reference_mobile      = models.CharField(max_length=15,blank=True)
    reg_date              = models.DateField(auto_now_add=True)
    status                = models.BooleanField(default=True)

    def __str__(self):
        return self.name+" ("+self.mobile+")"

    class Meta:
        verbose_name        ='Customer Registration'
        verbose_name_plural ='Customer Registrations'

class ProductCat(models.Model):
    branch             = models.ForeignKey(Branches, on_delete=models.CASCADE)    
    category_name      = models.CharField(max_length=100)
    status             = models.BooleanField(default=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name        ='Product Category'
        verbose_name_plural ='Product Categories'

class Product(models.Model):
    branch                      = models.ForeignKey(Branches, on_delete=models.CASCADE)
    category_name               = models.ForeignKey(ProductCat, on_delete=models.CASCADE)
    product_name                = models.CharField(max_length=100)
    brand_name                  = models.CharField(max_length=150, blank=True)
    product_image               = models.ImageField(upload_to="product_image/", blank=True)
    product_model_number        = models.CharField(max_length=100, blank=True)
    product_color               = models.CharField(max_length=50, blank=True)
    available_quantity          = models.IntegerField(default=1)
    total_quantity              = models.IntegerField(default=1)
    unit_price_by_cash          = models.FloatField(default=0)
    unit_price_by_installment   = models.FloatField(default=0)
    total_price                 = models.FloatField(default=0)
    buy_price                   = models.FloatField(default=0)
    maximum_discount            = models.FloatField(default=0, blank=True)
    discription                 = models.TextField(blank=True)
    status                      = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name        ='Product'
        verbose_name_plural ='Products'

class SaleProducts(models.Model):
    branch               = models.ForeignKey(Branches, on_delete=models.CASCADE)
    customer             = models.ForeignKey(CustomerRegistration, on_delete=models.CASCADE)
    product              = models.ForeignKey(Product, on_delete=models.CASCADE)
    payment_types = (
        ("1", "Full Payment"),
        ("2", "Installment"),
    )
    payment_type           = models.CharField(max_length=1, choices=payment_types)
    invoice                = models.IntegerField(blank = True, null=True)
    sale_quantity          = models.IntegerField(default=1)
    sale_unit_price        = models.IntegerField(default=1)
    discount               = models.FloatField(default=0)
    total_price            = models.FloatField(default=0)
    due_amount             = models.FloatField(default=0)
    comment                = models.TextField(blank=True)
    next_installment_date  = models.DateTimeField(auto_now_add=False, blank = True, null=True)
    next_installment_amount= models.IntegerField(default=0)
    sale_date              = models.DateField(auto_now_add = False)
    status                 = models.BooleanField(default=True)

    def __str__(self):
        return str(self.customer)

    class Meta:
        verbose_name        ='Product'
        verbose_name_plural ='Sales Products'

class InstallmentCollection(models.Model):
    invoice                  = models.IntegerField(blank = True, null=True)
    branch                   = models.ForeignKey(Branches, on_delete=models.CASCADE)
    customer                 = models.ForeignKey(CustomerRegistration, on_delete=models.CASCADE)
    product                  = models.ForeignKey(SaleProducts, on_delete=models.CASCADE)
    paid_amount              = models.FloatField(default=0)
    due_date                 = models.DateTimeField(auto_now_add=False)
    payment_date             = models.DateTimeField(auto_now_add=False)
    status                   = models.BooleanField(default=True)

    def __str__(self):
        return str(self.customer)+"-"+str(self.product)

    class Meta:
        verbose_name        ='Collection'
        verbose_name_plural ='Installment Collections'

showroom/templates/showroom/admin/report/daily_report.html
<html>
     <head>
         <title>Daily Report</title>
         <meta charset="utf-8" />
     </head>
     
     <body>
        <div class='wrapper'> 
            <table style="background-color: #eee;">
                <tr>
                    <td style="width:20%;">
                        <center>
                            <img style="height: 80px; width:80px;" src="{{company.domain_url}}/static/showroom/media/{{ company.branch_logo }}" alt="" >
                        </center>
                    </td>
                    <td style="width:60%;">
                        <h1 style="margin:0px;text-align:center;padding-top:15px;font-size:18px;">{{company.com_name}}</h1>
                        <h4 style="margin:0px;text-align:center;font-size:14px;">Proprietor: Admin</h4>
                        <h4 style="margin:0px;text-align:center;font-size:14px;">{{company.address}}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:14px;">{{company.email}}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:12px;">{% if company.mobile1 %}{{ company.mobile1 }}{% endif %}{% if company.mobile2 %}, {{ company.mobile2 }}{% endif %}</h4>
                        <h4 style="margin:0px;text-align:center;padding-bottom:7px;font-size:16px;"><u>Sales Report of {% now "DATETIME_FORMAT" %}</u></h4>
                    </td>
                    <td style="width:20%;">
                        <center>
                            <img style="height: 80px; width:80px;" src="{{company.domain_url}}/static/showroom/media/{{ company.company_logo }}" alt="" >
                        </center>
                    </td>
                </tr>
            </table>

            <table width="100%" style="margin-top:10px;border:1px solid gray;">
                <thead>
                    <tr>
                        <th style="width:40px;text-align:center;font-size:9px;padding-top:3px;background-color:#ddd;">SL</th>
                        <th style="text-align:left;font-size:9px;padding-left:3px;padding-top:3px;background-color:#ddd;">Product Name</th>
                        <th style="text-align:left;font-size:9px;padding-top:3px;padding-left:3px;background-color:#ddd;width:20%;">Bill Type</th>
                        <th style="text-align:right;font-size:9px;padding-right:3px;padding-top:3px;background-color:#ddd;">Product Price</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;padding-right:3px;background-color:#ddd;width:20%;">Sale Qty</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;padding-right:3px;background-color:#ddd;width:20%;">Discount</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;padding-right:3px;background-color:#ddd;width:10%;">Due Amount</th>
                        <th style="width:60px;text-align:left;font-size:9px;padding-left:3px;background-color:#ddd;width:20%;">Sale Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% if daliy_report %}
                        {% for data in daliy_report %}
                            <tr class="gradeX odd" role="row">
                                <td style="text-align:center;font-size:8px;padding-top:3px;width:10%;">{{ forloop.counter }}</td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:20%;"> {{data.product}}</td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:20%;"> {{data.get_payment_type_display}} </td>
                                {% if data.get_payment_type_display == "Full Payment" %}
                                    <td style="text-align:right;font-size:8px;padding-right:3px;padding-top:3px;width:20%;"> {{data.product.unit_price_by_cash}}</td>
                                {% else %}
                                    <td style="text-align:right;font-size:8px;padding-right:3px;padding-top:3px;width:20%;"> {{data.product.unit_price_by_installment}}</td>
                                {% endif %}
                                <td style="text-align:right;font-size:8px;padding-right:3px;padding-top:3px;width:20%;"> {{data.sale_quantity}} </td>
                                <td style="text-align:right;font-size:8px;padding-right:3px;padding-top:3px;width:20%;"> {{data.discount}}</td>
                                <td style="text-align:right;font-size:8px;padding-right:3px;width:30%;padding-left:3px;"> {{ data.due_amount }} </td>
                                <td style="text-align:left;font-size:8px;padding-top:3px;width:40%;padding-left:3px;"> {{ data.sale_date|date:"M-d-Y" }} </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                         <td style="text-align:center;font-size:10px;padding-top:3px; color:red;" colspan="7">No Data Found</td>
                    {% endif %}
                </tbody>
            </table>
        </div>
     </body>
 </html>

showroom/templates/showroom/admin/report/monthly_report.html
<html>
     <head>
         <title>Monthly Report | bdrecycle</title>
         <meta charset="utf-8" />
     </head>
     <body>
        <div class='wrapper' style="overflow-x:auto;"> 
            <table style="background-color: #eee;">
                <tr>
                    <td style="width:100%;">
                        <h1 style="margin:0px;text-align:center;padding-top:30px;font-size:24px;">{{company.com_name}}</h1>
                        <h4 style="margin:0px;text-align:center;font-size:12px;">{{ company.office_address }}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:12px;">{% if company.homepage_email1 %}{{ company.homepage_email1 }}{% endif %}{% if company.homepage_mobile %}, {{ company.homepage_mobile }}{% endif %}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:16px;">Monthly Report( {{ thismonth }} )</h4>
                    </td>
                </tr>
            </table>

            <table width="100%" style="margin-top:10px;border:1px solid gray;">
                <thead>
                    <tr>
                        <th style="width:40px;text-align:center;font-size:9px;padding-top:3px;background-color:#ddd;">SL</th>
                        <th style="text-align:left;font-size:9px;padding-left:3px;padding-top:3px;background-color:#ddd;">Item Category & Price</th>
                        <th style="text-align:left;font-size:9px;padding-top:3px;padding-left:3px;background-color:#ddd;width:20%;">Item Name</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;padding-right:3px;background-color:#ddd;width:20%;">Weight</th>
                        <th style="text-align:center;font-size:9px;padding-top:3px;background-color:#ddd;width:20%;">Pickup Date/Time</th>
                        <th style="text-align:left;font-size:9px;padding-top:3px;padding-left:3px;background-color:#ddd;width:20%;">Product For</th>
                        <th style="width:60px;text-align:left;font-size:9px;padding-left:3px;padding-top:3px;background-color:#ddd;width:200px;">Request Date</th>
                        <th style="width:60px;text-align:left;font-size:9px;padding-left:3px;padding-top:3px;background-color:#ddd;width:200px;">Accepted Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% if monthly_report %}
                        {% for data in monthly_report %}
                            <tr class="gradeX odd" role="row">
                                <td style="text-align:center;font-size:8px;padding-top:3px;width:10%;">{{ forloop.counter }}</td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:50%;"> {{data.category_name}}( {{data.category_name.price_per_kg}} )</td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:40%;"> {{data.item_name}} </td>
                                <td style="text-align:center;font-size:8px;padding-top:3px;width:20%;"> {{data.approximate_weight}} </td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:40%;"> {{data.pickup_date}}({{data.pickup_time}}) </td>
                                <td style="text-align:left;font-size:8px;padding-top:3px;width:30%;padding-left:3px;"> {{ data.get_product_for_display }} </td>
                                <td style="text-align:left;font-size:8px;padding-top:3px;width:40%;padding-left:3px;"> {{ data.request_date|date:"M-d-Y" }} </td>
                                <td style="text-align:left;font-size:8px;padding-top:3px;width:30%;padding-left:3px;color:green;" title="dfs">{{ data.completed_date|date:"M-d-Y" }} </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                         <td style="text-align:center;font-size:10px;padding-top:3px; color:red;" colspan="8">No Data Found</td>
                    {% endif %}
                </tbody>
            </table>
        </div>
     </body>
 </html>

showroom/templates/showroom/admin/report/yearly_report.html
<html>
     <head>
         <title>Daily Report</title>
         <meta charset="utf-8" />
     </head>
     
     <body>
        <div class='wrapper'> 
            <table style="background-color: #eee;">
                <tr>
                    <td style="width:100%;">
                        <h1 style="margin:0px;text-align:center;padding-top:30px;font-size:24px;">{{company.com_name}}({{company.branch}})</h1>
                        <h4 style="margin:0px;text-align:center;font-size:12px;">{{ company.address }}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:12px;">{{ company.email }}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:12px;">{% if company.mobile1 %}{{ company.mobile1 }}{% endif %}{% if company.mobile2 %}, {{ company.mobile2 }}{% endif %}</h4>
                        <h4 style="margin:0px;text-align:center;font-size:16px;">Daily Report( {{ currentdate }})</h4>
                    </td>
                </tr>
            </table>

            <table width="100%" style="margin-top:10px;border:1px solid gray;">
                <thead>
                    <tr>
                        <th style="width:40px;text-align:center;font-size:9px;padding-top:3px;background-color:#ddd;">SL</th>
                        <th style="text-align:left;font-size:9px;padding-left:3px;padding-top:3px;background-color:#ddd;">Product</th>
                        <th style="text-align:left;font-size:9px;padding-top:3px;padding-left:3px;background-color:#ddd;width:20%;">Payment Type</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;padding-right:3px;background-color:#ddd;width:20%;">Sale Quantity</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;background-color:#ddd;width:20%;">Discount</th>
                        <th style="text-align:right;font-size:9px;padding-top:3px;padding-left:3px;background-color:#ddd;width:20%;">Due Amount</th>
                        <th style="width:60px;text-align:left;font-size:9px;padding-left:3px;padding-top:3px;background-color:#ddd;width:200px;">Sale Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% if daliy_report %}
                        {% for data in daliy_report %}
                            <tr class="gradeX odd" role="row">
                                <td style="text-align:center;font-size:8px;padding-top:3px;width:10%;">{{ forloop.counter }}</td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:20%;"> {{data.product}}</td>
                                <td style="text-align:left;font-size:8px;padding-left:3px;padding-top:3px;width:20%;"> {{data.get_payment_type_display}} </td>
                                <td style="text-align:center;font-size:8px;padding-top:3px;width:20%;"> {{data.sale_quantity}} </td>
                                <td style="text-align:right;font-size:8px;padding-right:3px;padding-top:3px;width:40%;"> {{data.discount}}</td>
                                <td style="text-align:right;font-size:8px;padding-right:3px;width:30%;padding-left:3px;"> {{ data.due_amount }} </td>
                                <td style="text-align:left;font-size:8px;padding-top:3px;width:40%;padding-left:3px;"> {{ data.sale_date|date:"M-d-Y" }} </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                         <td style="text-align:center;font-size:10px;padding-top:3px; color:red;" colspan="7">No Data Found</td>
                    {% endif %}
                </tbody>
            </table>
        </div>
     </body>
 </html>